// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgNHvcywFraT4Dm9Inax2VhoKL8K3jlmo',
    appId: '1:139615055062:web:5445ca36ae0ab5fbd92d77',
    messagingSenderId: '139615055062',
    projectId: 'appdev-4558d',
    authDomain: 'appdev-4558d.firebaseapp.com',
    databaseURL: 'https://appdev-4558d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appdev-4558d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdflJSWdjG_r-4naqfsRXSFy-inV3EQBc',
    appId: '1:139615055062:android:e20e2f0d9d9b77d3d92d77',
    messagingSenderId: '139615055062',
    projectId: 'appdev-4558d',
    databaseURL: 'https://appdev-4558d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appdev-4558d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg4BHDUv1iAO3GWTJHXpY6sgq1K-KkVbg',
    appId: '1:139615055062:ios:1e328fb47c3f5c32d92d77',
    messagingSenderId: '139615055062',
    projectId: 'appdev-4558d',
    databaseURL: 'https://appdev-4558d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appdev-4558d.appspot.com',
    iosClientId: '139615055062-uhnjc3nmpic6c7msqhgmlhmoh6l4f3to.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg4BHDUv1iAO3GWTJHXpY6sgq1K-KkVbg',
    appId: '1:139615055062:ios:1e328fb47c3f5c32d92d77',
    messagingSenderId: '139615055062',
    projectId: 'appdev-4558d',
    databaseURL: 'https://appdev-4558d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appdev-4558d.appspot.com',
    iosClientId: '139615055062-uhnjc3nmpic6c7msqhgmlhmoh6l4f3to.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdev',
  );
}
